# XDG directories - https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

# base directory relative to which user-specific configuration files should be written
export XDG_CONFIG_HOME=$HOME/.config
# base directory relative to which user-specific data files should be written
export XDG_DATA_HOME=$HOME/.local/share
#export XDG_BIN_HOME=$HOME/.local/bin
#export XDG_LIB_HOME=$HOME/.local/lib
# base directory relative to which user-specific non-essential (cached) data should be written
export XDG_CACHE_HOME=$HOME/.cache
# defines the base directory relative to which user-specific non-essential runtime files and other file objects (such as sockets, named pipes, ...)
# export XDG_RUNTIME_DIR=/tmp

# export GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc
# export M2_HOME="$XDG_CONFIG_HOME"/maven/

export EDITOR=code
#export TERM=kitty

HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=10000
SAVEHIST=10000

_Z_DATA="$XDG_DATA_HOME"/z/data
# for intellij:  https://intellij-support.jetbrains.com/hc/en-us/community/posts/206845865--yjp-directory-any-value-at-all-
YOURKIT_HOME="$XDG_DATA_HOME"/yjp

if command -v npm >/dev/null 2>&1; then
    export PATH="`npm config get prefix`/bin:$PATH"
fi
export PATH="$HOME/bin:$PATH"

export LESSOPEN="| $(which highlight) %s --out-format xterm256 --line-numbers --quiet --force --style solarized-dark"
export LESS=" -R"

# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X';

export GRAALVM_HOME="$HOME/dev/tools/graalvm-ce-19.0.0"

export VOLTA_HOME="$HOME/.volta"
[ -s "$VOLTA_HOME/load.sh" ] && . "$VOLTA_HOME/load.sh"

export PATH="$VOLTA_HOME/bin:$PATH"