# XDG directories
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_BIN_HOME=$HOME/.local/bin
export XDG_LIB_HOME=$HOME/.local/lib
export XDG_CACHE_HOME=$HOME/.cache

export GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle
export YADM_HOME="$XDG_CONFIG_HOME/yadm"
export YADM_DATA="$XDG_DATA_HOME/yadm"
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc

# Alias respecting programs
alias mvm="mvn -gs "$XDG_CONFIG_HOME"/maven/settings.xml"
alias yadm="yadm -Y $YADM_HOME --yadm-repo $YADM_DATA/repo.git"

HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=10000
SAVEHIST=10000

_Z_DATA="$XDG_DATA_HOME"/z/data
