XDG_CONFIG_HOME=$HOME/.config
source "$XDG_CONFIG_HOME/zsh/zshenv"

source "$XDG_CONFIG_HOME/zsh/zgen/zgen.zsh"

# check if there's no init script
if ! zgen saved; then
    echo "Creating a zgen save"

    zgen oh-my-zsh

    # plugins
    #zgen oh-my-zsh plugins/git
    zgen oh-my-zsh plugins/github
    zgen oh-my-zsh plugins/sudo
    zgen oh-my-zsh plugins/command-not-found
    zgen oh-my-zsh plugins/sublime
    zgen oh-my-zsh plugins/npm
    zgen oh-my-zsh plugins/z
    zgen load zsh-users/zsh-syntax-highlighting

    # completions
    zgen load zsh-users/zsh-completions src

    # theme
    zgen oh-my-zsh themes/wedisagree

    # save all to init script
    zgen save
fi

# fzf
[ -f "$XDG_CONFIG_HOME/zsh/fzf.zsh" ] && source "$XDG_CONFIG_HOME/zsh/fzf.zsh"
