XDG_CONFIG_HOME=$HOME/.config

source "$XDG_CONFIG_HOME/zsh/zshenv"

source "$XDG_CONFIG_HOME/zsh/plugins.zsh"

source "$XDG_CONFIG_HOME/zsh/fzf.zsh"

source "$XDG_CONFIG_HOME/zsh/aliases.zsh"
source "$XDG_CONFIG_HOME/zsh/functions.zsh"

jdk 11