XDG_CONFIG_HOME=$HOME/.config

system_type=$(uname -s)

source "$XDG_CONFIG_HOME/zsh/zshenv"

source "$XDG_CONFIG_HOME/zsh/plugins.zsh"

source "$XDG_CONFIG_HOME/zsh/fzf.zsh"

source "$XDG_CONFIG_HOME/zsh/additional-completions.zsh"

source "$XDG_CONFIG_HOME/zsh/aliases.zsh"
if [ "$system_type" = "Darwin" ]; then
    source "$XDG_CONFIG_HOME/zsh/aliases-osx.zsh"
fi

source "$XDG_CONFIG_HOME/zsh/kubectl_aliases.zsh"
source "$XDG_CONFIG_HOME/zsh/functions.zsh"
if [ "$system_type" = "Darwin" ]; then
    source "$XDG_CONFIG_HOME/zsh/functions-osx.zsh"
    jdk 14
fi

#PATH="/home/geowarin/perl5/bin${PATH:+:${PATH}}"; export PATH;
#PERL5LIB="/home/geowarin/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
#PERL_LOCAL_LIB_ROOT="/home/geowarin/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
#PERL_MB_OPT="--install_base \"/home/geowarin/perl5\""; export PERL_MB_OPT;
#PERL_MM_OPT="INSTALL_BASE=/home/geowarin/perl5"; export PERL_MM_OPT;
