#!/bin/bash

# Brew
system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.config/brew/Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --file="$HOME/.config/brew/Brewfile"
  fi

fi

echo "Changing default shell: zsh"
chsh -s zsh

# For the history to be stored correctly
mkdir -p "$HOME/.local/share/zsh"