#!/bin/bash

# Brew
system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.config/brew/Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --file="$HOME/.config/brew/Brewfile"
  fi

  sudo sh -c "echo '/usr/local/bin/zsh' >> /etc/shells" && chsh -s /usr/local/bin/zsh

  # For the history to be stored correctly
  mkdir -p "$HOME/.local/share/zsh"
  mkdir -p "$HOME/.local/share/z"

  # iterm
  defaults write com.googlecode.iterm2 "PrefsCustomFolder" -string "$HOME/.config/iterm"
  defaults write com.googlecode.iterm2 "LoadPrefsFromCustomFolder" -bool true

  source "$HOME/.bin/macos.sh"
elif [ "$system_type" = "Linux" ]; then

  pacman -S zsh
  chsh -s /usr/bin/zsh

  # For the history to be stored correctly
  mkdir -p "$HOME/.local/share/zsh"

  # zplug
  yay -S zplug
  pacman -S fzf

  # i3
  pacman -S i3-gaps feh dunst 
  #albert
  yay -S polybar picom-jonaburg-git

  # zsh stuff
  pamac install highlight hub

  # utils - commandline
  pamac install tldr ripgrep fd docker openbsd-netcat

  # utils - gui
  pamac install zeal-git bitwarden

  # i3
  pamac install i3-gaps polybar feh dunst albert

  # rice
  pamac install xsettingsd

  # gnome-keyring

  # Remove this freakin kscreen hanging i3
  rm -rf .local/share/kscreen
fi

