#!/bin/bash

# Brew
system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.config/brew/Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --file="$HOME/.config/brew/Brewfile"
  fi

  sudo sh -c "echo '/usr/local/bin/zsh' >> /etc/shells" && chsh -s /usr/local/bin/zsh

  # For the history to be stored correctly
  mkdir -p "$HOME/.local/share/zsh"
  mkdir -p "$HOME/.local/share/z"

  # iterm
  defaults write com.googlecode.iterm2 "PrefsCustomFolder" -string "$HOME/.config/iterm"
  defaults write com.googlecode.iterm2 "LoadPrefsFromCustomFolder" -bool true

  source "$HOME/.bin/macos.sh"
elif [ "$system_type" = "Linux" ]; then
  chsh -s /usr/bin/zsh

  # For the history to be stored correctly
  mkdir -p "$HOME/.local/share/zsh"

  # zplug
  curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh

  pamac install fzf
fi

